meta_product_name: "The Fox Tail"
meta_title: "TheFoxTail - Track All Your Subscription Based Services"
meta_description: "The Fox Tail enables you to track all your subscription-based services in a singla place. No more hours spent on each one of your services to know how much time and money you spend with them. The Fox Tail takes care of it for you."
meta_image: "TheFoxTail_fb.png"
twitter_account: "@product_twitter_account"
